airflow:
  image:
    ##
    ## docker-airflow image
    repository: joaopmarques66/airflow
    ##
    ## image tag
    tag: 1.0
    ##
    ## Image pull policy
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
  executor: Kubernetes
  service:
    type: LoadBalancer
  config:
  #  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow-docker-local
  #  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1
  #  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: Never

  #  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
  #  AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
  #  AIRFLOW__KUBERNETES__NAMESPACE: airflow

  #  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:airflow@airflow-postgresql:5432/airflow

persistence:
  enabled: true
  existingClaim: ''

workers:
  enabled: false

postgresql:
  enabled: true

redis:
  enabled: false