uid: 1000
images:
  airflow:
    repository: joaopmarques66/dags
    tag: 0.0.3
    pullPolicy: IfNotPresent
rbacEnabled: True
webserver:
  defaultUser:
    enabled: False
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
statsd:
  enabled: False
env:
  - name: AIRFLOW__CORE__PARALLELISM
    value: 4
  - name: AIRFLOW__CORE__DAG_CONCURRENCY
    value: 1

scheduler:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

postgresql:
  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000

  resources:
    requests:
      memory: 128Mi
      cpu: 250m

  volumePermissions:
    ## Init container Security Context
    ## Note: the chown of the data folder is done to securityContext.runAsUser
    ## and not the below volumePermissions.securityContext.runAsUser
    ## When runAsUser is set to special value "auto", init container will try to chwon the
    ## data folder to autodetermined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
    ## "auto" is especially useful for OpenShift which has scc with dynamic userids (and 0 is not allowed).
    ## You may want to use this volumePermissions.securityContext.runAsUser="auto" in combination with
    ## pod securityContext.enabled=false and shmVolume.chmod.enabled=false
    ##
    securityContext:
      runAsUser: 1000
  metrics:
    ## Define additional custom metrics
    ## ref: https://github.com/wrouesnel/postgres_exporter#adding-new-metrics-via-a-config-file
    # customMetrics:
    #   pg_database:
    #     query: "SELECT d.datname AS name, CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE 0 END AS size FROM pg_catalog.pg_database d where datname not in ('template0', 'template1', 'postgres')"
    #     metrics:
    #       - name:
    #           usage: "LABEL"
    #           description: "Name of the database"
    #       - size_bytes:
    #           usage: "GAUGE"
    #           description: "Size of the database in bytes"
    ## Pod Security Context
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
    ##
    securityContext:
      enabled: false
      runAsUser: 1000
  persistence:
    enabled: False
  shmVolume:
    chmod:
      enabled: False